services:
  app:
    image: ghcr.io/sku-semihkt/sku-thon-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/skuthon
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - skuthon-net
    restart: unless-stopped

networks:
  skuthon-net:
    external: true
    name: skuthon-net
