spring:
  application:
    name: sku-thon
  profiles:
    include: secret
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cors:
  allowed-origins: http://localhost:5173,https://barbelllog.netlify.app, https://api.likelion.store

file:
  upload-dir: /uploads